### ISSUE TITLE
Failed to install in a Linux system with Python 2.7.3

### ISSUE THREAD

**Issue by debojyoti-majumder** [JeanSebTr/node-python#1]
I have got this output while I was trying to build node-python and after this it didn't got installed on my system.

I have node.js and npm are configured and I have downloaded other packages and installed successfully on this system.

There seems to be a problem with the "binding" module. Have I missed something??
Any suggestion or comment will be very helpful.

bash-4.2$ npm install node-python
npm http GET https://registry.npmjs.org/node-python
npm http 304 https://registry.npmjs.org/node-python

> node-python@0.0.2 install /home/auser/startup/python-exp1/node_modules/node-python
> node-gyp rebuild

make: Entering directory `/home/auser/startup/python-exp1/node_modules/node-python/build'
  CXX(target) Release/obj.target/binding/binding.o
../binding.cc:14:30: fatal error: python2.6/Python.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/binding/binding.o] Error 1
make: Leaving directory`/home/auser/startup/python-exp1/node_modules/node-python/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.8.4-102.fc17.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/auser/startup/python-exp1/node_modules/node-python
gyp ERR! node -v v0.10.12
gyp ERR! node-gyp -v v0.10.0
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
bash-4.2$ npm install node-python

> node-python@0.0.2 install /home/auser/startup/python-exp1/node_modules/node-python
> node-gyp rebuild

make: Entering directory `/home/auser/startup/python-exp1/node_modules/node-python/build'
  CXX(target) Release/obj.target/binding/binding.o
../binding.cc:14:30: fatal error: python2.6/Python.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/binding/binding.o] Error 1
make: Leaving directory`/home/auser/startup/python-exp1/node_modules/node-python/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.8.4-102.fc17.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/auser/startup/python-exp1/node_modules/node-python
gyp ERR! node -v v0.10.12
gyp ERR! node-gyp -v v0.10.0
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by JeanSebTr** [comment]
Hi !

the original project used a specific include for OSX. It's still this code that's on NPM right now.

I had fixed it in the sources on master but I didn't have added the required include for linux in binding.gyp yet.
I'm launching a VM right now to fix it.

**Comment by JeanSebTr** [comment]
It's now fixed in node-python v0.0.3

Don't forget to `#apt-get install python-dev`

**Comment by debojyoti-majumder** [comment]
Awesome!! It worked out fine. Many thanks...
