### ISSUE TITLE
Problem with node-python

### ISSUE THREAD

**Issue by saikatbhattacharya** [JeanSebTr/node-python#3]
I am working on node.js and I have to work with python script invoking in node. So, I was trying to install node-python. But it is giving some error while I was trying to install it with npm. The problem is occurring with both windows and Ubuntu. 
I am attaching the screenshot. If you kindly help me regarding this, I will be glad.
![node-python](https://f.cloud.github.com/assets/5483620/1162575/7fad4990-201c-11e3-8d2f-bd8b9ac75090.jpg)

**Comment by JeanSebTr** [comment]
That looks a lot like TooTallNate/node-gyp#84

Are you able to compile other native modules ?
For example: `npm install bson`

**Comment by saikatbhattacharya** [comment]
Hi,
Yeah, those are working.
Regards
Saikat Bhattacharya 
Sr. Developer – Mobility Products
Cognizant Technology Service

**Comment by pluto5004** [comment]
From your system, npm is not able to download node v.0.8.x. If you are using any proxy, that might be blocking the content.

**Comment by vlrprbttst** [comment]
i have the same problem on windows
![gihtuvs](https://cloud.githubusercontent.com/assets/4832752/4023167/e940c828-2b79-11e4-939c-4a52e4ba5572.png)
