### ISSUE TITLE
Importing of Modules Not Working

### ISSUE THREAD

**Issue by kgrvamsi** [JeanSebTr/node-python#5]
Hello,

I'm Trying to Invoke some of the Modules through Nodejs and seems like i end up with undefined name sort errors.

scenario---- 

Step-1 -- 

Installed a Module in Python Called Troposphere through PIP
------------ sudo pip install troposphere

Step -2 -- 

Called the Module in Nodejs using Expressjs Framework in one of the Routes
--------- var trop = python.import('troposphere').ec2; -- (Here dont know how this sentence in Python works out through bridge  'import troposphere.ec2 as ec2')

Step -3

called a Function inside the Module in nodejs like this
------------ trop.add_resource(instance);

Result ---- 

Cannot call method 'add_resource of undefined

Can you help me out on this Issue on how to use the module properly to invoke the python module in nodejs .

**Comment by pranayiitd** [comment]
Similar problem here. Any solution or fixes ?
