### ISSUE TITLE
Install doesn't seem to work

### ISSUE THREAD

**Issue by ramotswa** [JeanSebTr/node-python#6]
Hey - I get this error - any ideas?

Thanks

npm http GET https://registry.npmjs.org/node-python
npm http 304 https://registry.npmjs.org/node-python
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bindings

> node-python@0.0.4 install /home/toby/node_modules/node-python
> node-gyp rebuild

/bin/sh: 1: python-config: not found
gyp: Call to 'python-config --libs' returned exit status 127.
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.8.0-29-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/toby/node_modules/node-python
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! node-python@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-python@0.0.4 install script.
npm ERR! This is most likely a problem with the node-python package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-python
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.0-29-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node-python"
npm ERR! cwd /home/toby
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/toby/npm-debug.log
npm ERR! not ok code 0

**Comment by JeanSebTr** [comment]
Hi,

I see you are using Linux, if it's Ubuntu you must install python-dev first. The build use `python-config` to find the compiler options and it can find this command now.

**Comment by JeanSebTr** [comment]
Same as #8 
Just added info to the github's README
