### ISSUE TITLE
undefined symbols when importing some modules

### ISSUE THREAD

**Issue by silvermangb** [JeanSebTr/node-python#7]
I have a very simple python script

In directory mypython
# file: **init**.py

import sys
import datetime

And, I have a very simple node script

/_file: p.js_/
var python = require('node-python')
var python_sys = python.import('sys')
var python_sys_path = python_sys.path
python_sys_path.append('.')
var mypython = python.import('mypython')

When I run it

node p.js

I get this:
/home/nokia/src/repo/tng/trunk/apps/nemo/services/meetup/p.js:5
var mypython = python.import('mypython')
                            ^
Error: /usr/lib/python2.7/lib-dynload/datetime.so: undefined symbol: PyExc_SystemError
    at Object.<anonymous> (/home/nokia/src/repo/tng/trunk/apps/nemo/services/meetup/p.js:5:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

So, it does load my python script. If **init**.py simply had 

print 'hello world'

It works.

This is happening on debian 7 (wheezy).

**Comment by silvermangb** [comment]
My python script file has the proper naming convention, with leading and trailing underscores. This posting tool is removing them.

**Comment by JeanSebTr** [comment]
datetime.so doesn't seem to have been compiled with the same python library as node-python

What's the output of `python-config --libs` ?

silvermangb notifications@github.com a écrit :

**Comment by silvermangb** [comment]
I see

-lpthread -ldl -lutil -lm -lpython2.7

**Comment by silvermangb** [comment]
This may be a hack, but, added code to node-python binding.cc that uses dlopen to load libpython2.7 when node-python's so is loaded and the problem is gone. At least for some simpe tests.
